server:
  AppMode: debug
  HttpPort: :8080

database:
  Db: MYSQL
  DbHost: db
  DbPort: 3306
  DbUser: root
  DbPassWord: rootpassword
  DbName: yanblog
  
# openssl rand -hex 32
JwtKey: 1234567890

weather:
  Provider: openweathermap
  ApiKey: 
  DefaultCity: Hefei