server:
  AppMode: debug
  HttpPort: :8080

database:
  Db: MYSQL
  DbHost: db
  DbPort: 3306
  DbUser: root
  DbPassWord: rootpassword
  DbName: yanblog
  
# openssl rand -hex 32
JwtKey: 2a959d62cef45c07c167a280dd370c34c38ccfe4d378b1440bf5f68da928f951

weather:
  Provider: openweathermap
  ApiKey: 
  DefaultCity: Hefei