server:
  AppMode: debug
  HttpPort: :8080
  # 站点域名，用于生成 Sitemap (末尾不带 /)
  SiteUrl: 

database:
  Db: MYSQL
  DbHost: db
  DbPort: 3306
  DbUser: root
  DbPassWord: rootpassword
  DbName: yanblog
  
# openssl rand -hex 32
JwtKey: 

weather:
  Provider: openweathermap
  ApiKey: 
  DefaultCity: Hefei

# 前端配置文件路径
FrontEndConfigPath: web/frontend/public/config.yaml