server:
  AppMode: debug
  HttpPort: localhost:8080

database:
  Db: 
  DbHost: 
  DbPort: 
  DbUser: 
  DbPassWord: 
  DbName: 
  
# openssl rand -hex 32（使用这个命令生成密钥，修改为你自己的密钥）
JwtKey: 1234567890

weather:
  Provider: openweathermap
  ApiKey: 
  DefaultCity: 