# 配置博客信息
blog_name: "言盐盐的博客"
author_name: "yaan"
author_avatar: "/src/assets/avatar.jpg"
author_bio: "欢迎光临 (￣▽￣)~*"

# 主页 Hero 区域标题
hero:
  title: "草木山石<br>日月星辰"
  subtitle: "yaan's blog"
  welcome: "Welcome to<br>Yaan's Blog"
  welcome_image: "/src/assets/img/1412.jpg"

# 个人卡片名言
quotes:
  - "月亮想着我的心事，一只猫吃了我的奶酪"
  - "草木山石，日月星辰"
  - "雾霭山岚，风光雨霁"

logo_text: "言盐盐的博客"
logo_image: "/src/assets/yan_icon/yaan.png"
favicon: "/favicon.ico"

# 后台管理地址
admin_url: "http://localhost:3001"

# 标签页内容
page_title:
  # 在当前页显示的标题
  default: "Yaanlaan Blog"
  # 不在当前页时显示的标题
  blur: "言盐盐的博客(O_O)"

# 你的阿里图标链接或者下载到本地
iconfont_url: "/public/iconfont/iconfont.css"

# 主页的快捷链接，实际上可以指向你服务器上的其他服务
shortcuts:
  - name: "知乎"
    url: "https://www.zhihu.com/"
    icon: "icon-document"
    color: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)"
  - name: "Bilibili"
    url: "https://www.bilibili.com/"
    icon: "icon-ppt"
    color: "linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)"
  - name: "Github"
    url: "https://github.com/"
    icon: "icon-folder"
    color: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)"

footer:
  # 页脚相关信息
  copyright: "Copyright ©2022-2025 言盐盐 All Rights Reserved"
  email: "yanxia2425@foxmail.com"
  
  # ICP 备案信息
  icp:
    show: true
    text: "京ICP备xxxxxx号"
    link: "https://beian.miit.gov.cn"

  powered_by: "yanblog"
  powered_by_link: "https://github.com/yaanlaan/yanblog.git"

  # 页脚作品集
  portfolio:
    show: true
    title: "作品集"
    icon: "icon-book"
    items:
      - name: "yanblog"
        url: "https://github.com/yaanlaan/yanblog.git"
        icon: "icon-lianjie"

  # 页脚相关链接
  related_links:
    show: true
    title: "相关链接"
    items:
      - name: "本博客参考博客链接（知乎：恢锦）"
        url: "https://kirigaya.cn"
        icon: "icon-lianjie"

# 个人卡片下方的联系方式
socials:
  - name: "Github"
    url: "https://github.com/yaanlaan"
    icon: "icon-github-fill"
    color: "#000000"
    is_circle: true
  - name: "Bilibili"
    url: "https://bilibili.com"
    icon: "icon-bilibili-line"
    color: "#fb7299"
    is_circle: true
  - name: "Email"
    url: "mailto:yanxia2425@foxmail.com"
    icon: "icon-email"
    color: "#0000ff"
    is_circle: true
  - name: "知乎"
    url: "https://www.zhihu.com"
    icon: "icon-zhihu-circle-fill"
    color: "#2c74ff"
    is_circle: true

# 关于页的联系方式
contacts:
  show: true
  items:
    - name: "Email"
      url: "mailto:yanxia2425@foxmail.com"
      icon: "icon-email"
      color: "#0000ff"
      is_circle: true
    - name: "Github"
      url: "https://github.com/yaanlaan"
      icon: "icon-github-fill"
      color: "#000000"
      is_circle: true
    - name: "Bilibili"
      url: "https://space.bilibili.com"
      icon: "icon-bilibili-line"
      color: "#fb7299"
      is_circle: true
    - name: "知乎"
      url: "https://www.zhihu.com"
      icon: "icon-zhihu-circle-fill"
      color: "#2c74ff"
      is_circle: true

# 关于页的音乐播放器
music_player:
  show: ture
  url: "//music.163.com/outchain/player?type=2&id=555503430&auto=0&height=66"
